# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gha-minor-patch:
        applies-to: version-updates
        update-types:
          - "patch"
          - "minor"
  - package-ecosystem: "npm"
    directory: "/action"
    schedule:
      interval: "weekly"
    groups:
      npm-minor-patch:
        applies-to: version-updates
        update-types:
          - "patch"
          - "minor"
  - package-ecosystem: "gomod"
    directory: "/agent"
    schedule:
      interval: "weekly"
    groups:
      go-minor-patch:
        applies-to: version-updates
        update-types:
          - "patch"
          - "minor"
