name: Bullfrog Secure Runner
description: Controls outbound traffic (egress) to secure GitHub Actions workflows.

inputs:
  allowed-ips:
    description: "List of allowed IP addresses for outbound connections."
  allowed-domains:
    description: "List of allowed domains for outbound connections."
  dns-policy:
    description: "DNS policy to enforce when egress-policy is set to 'block'. Options: 'allowed-domains-only' (default) or 'any'."
    default: "allowed-domains-only"
  egress-policy:
    description: "The egress policy to enforce. Options: 'audit' (default) or 'block'."
    type: string
    default: "audit"
  log-directory:
    description: "Directory to store log files."
    type: string
    default: ${{ runner.temp }}/agent-logs

runs:
  using: "node20"
  main: "action/dist/main.js"
  post: "action/dist/post.js"
